create table w2_table(
W2_NO NUMBER(5),
W2 VARCHAR2(30),
W2_H VARCHAR2(50),
constraint PK_W2_NO PRIMARY KEY(W2_NO));

CREATE SEQUENCE W2_SQ
START WITH 1 
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 10000 
NOCYCLE 
NOCACHE;

INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'소식지','뉴스레터');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'보호난간','가드레일');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'상승효과','시너지효과');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'점검표','체크리스트');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'표내는곳','개찰구');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'표사는곳','매표소');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'홀몸노인','독거노인');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'여름철','하절기');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'겨울철','동절기');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'갖춤서류','구비서류');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'증거서류','증빙서류');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'붙임서류','첨부서류');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'갈아타는곳','환승역');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'타는곳','승강장');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'내용','적요');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'서식','템플릿');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'임무','미션');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'보내다','송부하다');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'주고받다','수수하다');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'받는곳','수신처');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'주고받기','양도양수');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'승강장안전문','스크린도어');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'배려석','노약자석');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'현장방문','시찰');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'모으다','취합하다');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'성과급','인센티브(incentive)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'사업','프로젝트(project)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'안내서','매뉴얼(manual)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'귀금속','주얼리(jewelry)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'민관협력','거버넌스(governance)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'기자단현장방문','프레스 투어(press tour)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'정원가꾸기','가드닝(gardening)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'전문안내원','도슨트(docent)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'틀','프레임(frame)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'종합계획','마스터플랜(master plan)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'자르기 ','커팅(cutting)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'입소문','바이럴(viral)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'내려받기','다운로드(download)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'기반','인프라((Infrastructure)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'이야기','스토리텔링(storytelling)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'축제','페스티벌(festival)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'상생','윈윈(win-win)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'위험','리스크(risk)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'단계별계획','로드맵(road map)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'회의','콘퍼런스(conference)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'전시실','갤러리(gallery)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'경로','루트(route)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'개발제한구역','그린벨트(green belt)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'치유','힐링(healing)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'누리소통망','에스앤에스(SNS)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'무인안내기','키오스크(kiosk)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'심장충격기','자동제세동기');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'황금시간','골든타임(golden time)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'알림','고지');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'바람','요망');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'행사','이벤트(Event)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'구역','존(Zone)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'표어','슬로건(Slogan)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'공동연수','워크숍(Workshop)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'띠광고','배너(banner)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'순환버스','셔틀 버스(Shuttle bus)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'찾음표','견출지');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'자르는선','절취선');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'경위서','시말서');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'임시처분','가처분');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'수습','견습');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'목적지','행선지');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'먹는물','음용수');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'남은음식','잔반');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'밥값','식비,식대');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'넘겨받다','인수하다');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'넘겨주다','인계하다');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'뽑다','차출하다');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'부르다','호출하다');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'돌려보기','회람');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'틀','와쿠(와꾸)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'혼잡시간','러시아워(rush hour)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'큰비','호우');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'승부','쇼부');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'흠집','기스');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'멋지다','간지나다');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'노동자','노가다');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'투정','땡깡');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'곁들이찬','쓰키다시');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'가짜','가라');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'다중작업','멀티태스킹');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'벼룩시장','플리마켓 (프리마켓)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'새싹기업','스타트업');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'공개자료','오픈소스');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'어려운이웃','불우 이웃');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'한부모','편부, 편모 ');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'실적자료집','포트폴리오');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'영향력자','인플루언서');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'상징건물','랜드마크');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'햇빛충전소','솔라스테이션');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'안내서','브로셔, 브로슈어');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'이용실적','마일리지');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'누리저장소','웹하드');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'소통공간','커뮤니티 공간(community space)');		
INSERT INTO W2_TABLE VALUES(W2_SQ.NEXTVAL,'비상호출','비상콜');		